### ISSUE TITLE
Great initiative!

### ISSUE THREAD

**Issue by Jordy-VL** [neulab/ExplainaBoard#1]
Hi, 

I was looking at explainaboard online and immediately some questions popped to mind:

I found that for NER, there was no calibration analysis. I was wondering if this is something you would like to support in the future? 

Also, will you keep model binaries, as a model zoo? Or only analysis on benchmark datasets? 
I believe a large-scale model zoo is missing in NLP, but the collection thereof might even be more complex. What are your thoughts?

Cheers,

Jordy

**Comment by pfliu-nlp** [comment]
Hi, Jordy

Thanks a lot for your interesting questions!
>"Also, will you keep model binaries, as a model zoo? Or only analysis on benchmark datasets?"
True! And yes, we actually have thought about this. Our current plan is to release output files of predictions first. But, we're thinking about the possibility of collecting binary models and releasing them as well by collaborating with Huggingface.

> "I found that for NER, there was no calibration analysis. I was wondering if this is something you would like to support in the future?"
Yeah, currently, the calibration functionality only supports classification-based tasks (text classification or NLI). But we will make it on the NER task soon.

**Comment by pfliu-nlp** [comment]
Yeah, good suggestions
