### ISSUE TITLE
Bug: Leaderboards seem to be non-functional?

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#101]
Going to the leaderboards seems to have an infinite "loading" menu and no functionality:
https://explainaboard.inspiredco.ai/leaderboards/machine-translation

I suspect that this might be because there's no data, but we might want to hide any leaderboards that aren't functional at the moment (or hide the "leaderboards" tab entirely if it's not working)

**Comment by lyuyangh** [comment]
Looking at the logs, it seems that the "tasks" field is missing for some of the datasets and those datasets are selected for at least one of the systems. I'm not quite sure how that happened. I'll provide a fix today.

**Comment by lyuyangh** [comment]
fixed in https://github.com/neulab/explainaboard_web/commit/ff201dcc152ebc39198a0cc6cb92a704c9262bad Also, turned on MT.
