### ISSUE TITLE
More extensive support for training-set dependent features

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#106]
Many informative features are dependent on the training set or features calculated from the training set being available. 

Currently, this is dependent on pre-computed features being included in the ExplainaBoard repository, such as below: https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/builders/named_entity_recognition.py#L41

This seems like it won’t scale if we want to, for example, support all of the datasets included in DataLab. It seems like it’d be good to take a strategy such as having a “cache” directory where datasets (or pre-computed features) are stored, and the ExplainaBoard SDK
1. checks the cache for existence of these features
2. if it doesn’t exist, checks DataLab for the dataset name
3. if it still doesn’t exist, throw an error

I'd be happy to start looking at this if this seems like a reasonable strategy.

**Comment by pfliu-nlp** [comment]
Besides the above stuff, I think some important questions I want to figure out are:
(1) which types of task do we aim to explore first
(2) what will be a `good` training set dependent features for these task?
We could have a list based on the above questions first.

**Comment by neubig** [comment]
Good questions!

If you want two really simple training set dependent feature that are task independent, and also simple to implement in our current framework we could do:
1. Number of unknown words in the input sentence (presumably more unknowns = more difficulty)
2. Average frequency rank of words in the sentence, such as the right side of figure 3 in [the seq2seq models paper](https://arxiv.org/pdf/1409.3215.pdf) (presumably higher rank = more difficulty)

Once we have a good framework to handle training set dependent features in a generalizable way I'm sure we can think of more task-by-task, but maybe it'd be good to have some simple task-independent ones for now?

**Comment by pfliu-nlp** [comment]
Yeah, I'm think whether the differences among feature types will effect the design of general framework to do this.
These two task-irrelevant features are good. Anyway, I will try to explore more first and put them [here](https://docs.google.com/document/d/1QCof9k2wcE1G64VHn2-Aih_Yz8DdZ3fHc2Io4--sxBE/edit?usp=sharing)

**Comment by pfliu-nlp** [comment]
Regarding 2, @neubig 
Yes, we need to set up a permission strategy. So far, I just let Yang help out with implementing an API that we can use to read and write some information from MongoDB.
Two follow-up questions:
(1) what would be a good method to achieve this? ( It seems like we'll certainly need to have a permissioning system for this)
(2) Each document of MongoDB cannot stored too large files, which will limits our training-set dependent features. For example, we cannot have OOV feature for cnn_dailymail dataset. Do you think we should solve it or bypass it (i.e., not having this feature)
