### ISSUE TITLE
ExplainaBoard repo is very big, so cloning is slow

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#113]
The full history of the ExplainaBoard repo is quite big, and because of this a `git clone` on the ExplainaBoard repository takes a really long time on a slow-ish internet connection.

It seems the largest dataset is this, which is 50M or so, but there are others too: https://github.com/neulab/ExplainaBoard/tree/main/data/datasets/fb15k_237

Given that one goal of ExplainaBoard is to cover basically most NLP datasets, only a subset of which will be used by any individual user, I think that the only datasets that should be checked in to the actual repo should be tiny ones that are used for demonstration purposes. All other datasets can be downloaded on-the-fly from a source such as DataLab.

Because of this, I would suggest that we remove the larger datasets from the repo, and remove their files from the git history:
https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-the-git-repository

**Comment by pfliu-nlp** [comment]
goog suggestion, and it should be fixed.
