### ISSUE TITLE
error logs when deployed in web app (kb task)

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#122]
![image](https://user-images.githubusercontent.com/59123869/157882350-e97fc4c6-57a9-4527-895c-10634d86bc2b.png)

the file `entity_type_level_map.json` should be placed in a right place (@hwidjaja ).
I will address this later.

**Comment by pfliu-nlp** [comment]
Fixed but have a new bug?

![image](https://user-images.githubusercontent.com/59123869/158002941-2c06efad-c8aa-47f9-806b-0be17da011f8.png)

**Comment by pfliu-nlp** [comment]
This pr can fix the above bug, but @hwidjaja it would be nice if you can check the functionality of customized features by:
* adding more unittest for kg_link_tail_prediction tasks [here](https://github.com/neulab/ExplainaBoard/tree/main/explainaboard/tests) in different testing scenarios (e.g, using custmoized features, or non-customized) to see if the output buckets are as expected.

**Comment by neubig** [comment]
Is this fixed?
