### ISSUE TITLE
Setting confidence score to None/null instead of zero if unavailable

### ISSUE THREAD

**Issue by OscarWang114** [neulab/ExplainaBoard#135]
Currently, it seems that the confidence scores (low and up) are set to zero if they are unavailable in the analysis. It would be better if we can set it to `None` in python and output `null` in JSON. It is more meaningful semantically and helps solve [this web interface bug](https://github.com/neulab/explainaboard_web/issues/111) I am fixing.

The bug is caused by the logic that confidence score points are only plotted when they are not zero (because my assumption is zero means they are not available). I missed the corner case where zero confidence scores can also be caused by a bucket with a score of zero. This could be fixed easily if SDK outputs `null` instead of zero.

**Comment by neubig** [comment]
I can do this.

**Comment by OscarWang114** [comment]
@neubig Thanks for the reply and taking on the issue! Looking forward to the PR. If at any moment you need to prioritize other matters, I'm happy to work on it too. 😀
