### ISSUE TITLE
Bug(?): the evaluation results using `ExactMatchQA` on extractive qa task

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#197]
Reported from Jinlan: the evaluation results using `ExactMatchQA` on the extractive QA task are significantly lower than the one calculated by the previous version of SDK

**Comment by pfliu-nlp** [comment]
Aha, thanks Graham, I'm looking now, by comparing with the old branch, I found the `normalize_answer` function has been re-written, but I think they are not completely the same, is this intended?

**Comment by neubig** [comment]
No, they were supposed to be the same. If it's not that's my mistake. Thanks for fixing this and sorry for the bug!

**Comment by neubig** [comment]
Being handled by this PR: https://github.com/neulab/ExplainaBoard/pull/198
