### ISSUE TITLE
Unify typing of metric_stats

### ISSUE THREAD

**Issue by OscarWang114** [neulab/ExplainaBoard#210]
`metric_stats` has a variety of types: `Any`, `list[MetricStats]`, `Optional[list[MetricStats]]`. I'd like to work on unifying them. Two things I'd like to know: 

1. If `metric_stats`is empty, is it `None` or an empty `list`?
2. Is its type always `list[MetricStats]`? Are there any exceptions?

**Comment by neubig** [comment]
I think it's safe to assume that the type is always `list[MetricStats]`!
