### ISSUE TITLE
test_no_user_defined_features in TestKgLinkTailPrediction fails

### ISSUE THREAD

**Issue by tetsuok** [neulab/ExplainaBoard#218]
Hi, I noticed CI in this repo keeps failing due to test failures. The tests are failing for several reasons. 
I think developers can get more confidence if the test failures get fixed when they make some fundamental changes
and they merge pull requests from contributors.

The one of the failures is `test_no_user_defined_features` in `TestKgLinkTailPrediction` class in `explainaboard/tests/test_dynamic_hits_metric.py`. As far as I understand, the root cause of the issue is that 
the data format of the JSON file, `test-kg-link-tail-prediction.json`, read by the test script doesn't match what `KgLinkTailPredictionLoader`'s `load` method expects. I'm not familiar with the link prediction task and 
dataset used in the test, though.
For details, see the repro step, result, and data format sections below.

### Environment
- Debian GNU/Linux 10 (buster)
- python 3.7.3

### Repro steps

```
git clone git@github.com:tetsuok/ExplainaBoard.git
cd ExplainaBoard
python3 -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip
pip install .
python -m spacy download en_core_web_sm
python -m nltk.downloader punkt
python -m unittest -v explainaboard/tests/test_dynamic_hits_metric.py
```

### Output

```
test_no_user_defined_features (explainaboard.tests.test_dynamic_hits_metric.TestKgLinkTailPrediction) ... ERROR

======================================================================
ERROR: test_no_user_defined_features (explainaboard.tests.test_dynamic_hits_metric.TestKgLinkTailPrediction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/t/ExplainaBoard/explainaboard/tests/test_dynamic_hits_metric.py", line 21, in test_no_user_defined_features
    data = loader.load()
  File "/home/t/ExplainaBoard/explainaboard/loaders/kg_link_tail_prediction.py", line 69, in load
    "true_head": features_dict["gold_head"],
TypeError: list indices must be integers or slices, not str

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

### Data format

`kg_link_tail_prediction.py` expects keys such as "gold_head" in the JSON file for each example, but `test-kg-link-tail-prediction.json` doesn't have such keys:

```
$ head explainaboard/tests/artifacts/test-kg-link-tail-prediction.json
{
    "Z\u00fcrich\t/travel/travel_destination/climate./travel/travel_destination_monthly_climate/month\tOctober": [
        "October",
        "Fields Medal",
        "pound sterling",
        "Euro",
        "Australian dollar"
    ],
    "autoharp\t/music/performance_role/regular_performances./music/group_membership/group\tHeart": [
        "The Mothers of Invention",
$
```

To make the test working, we probably need to fix the format as in `test-kg-prediction-no-user-defined-new.json`:

```
$ head -n 15 explainaboard/tests/artifacts/test-kg-prediction-no-user-defined-new.json
{
    "1": {
        "gold_head": "/m/08966",
        "gold_predicate": "/travel/travel_destination/climate./travel/travel_destination_monthly_climate/month",
        "gold_tail": "/m/05lf_",
        "predict": "tail",
        "predictions": [
            "/m/05lf_",
            "/m/02x_y",
            "/m/01nv4h",
            "/m/02l6h",
            "/m/0kz1h"
        ]
    },
    "2": {
```

**Comment by pfliu-nlp** [comment]
Thanks a bunch, @tetsuok for your nice capture! Your suggestion is correct. We actually have fixed this in this PR: https://github.com/neulab/ExplainaBoard/pulls but haven't merged it currently (will do it ASAP)

**Comment by pfliu-nlp** [comment]
this should be fixed since this PR has been merged: https://github.com/neulab/ExplainaBoard/pull/217
