### ISSUE TITLE
我当上传自己系统的输出时，出现了如下错误

### ISSUE THREAD

**Issue by Hou-jing** [neulab/ExplainaBoard#221]
![image](https://user-images.githubusercontent.com/75936962/162551213-43732907-83e0-48fb-9a45-9acc2f4d8ab4.png)

**Comment by pfliu-nlp** [comment]
Hi, @Hou-jing, thanks for your attention. We actually have upgraded our system output submission UI. Which tasks are you focusing on now? I can share our beta version with you if your task has already been supported by our new version.

**Comment by neubig** [comment]
The new beta site is available here: https://explainaboard.inspiredco.ai/

Please submit if you're interested!
