### ISSUE TITLE
Better support for listing/inspecting DataLab datasets

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#234]
Now that ExplainaBoard easily supports datasets input by DataLab, we need

* [ ] A list of all of the supported datasets so users know which ones they can select
* [ ] Instructions on how to add a dataset if they don't exist
* [ ] A programmatic way to access this list (for use in the web interface, etc.)
* [ ] A way to dump or manually inspect the datasets (so users can tell what order the data entries are in, or debug problems like their outputs not having the same number of entries as the dataset in datalab)

**Comment by neubig** [comment]
Update: this directory has a list of all datasets https://github.com/ExpressAI/DataLab/tree/main/datasets

But more information should be available. See this issue opened upstream: https://github.com/ExpressAI/DataLab/issues/135

**Comment by lyuyangh** [comment]
Adding on to that, I think we also need a programmatic way of getting this list (and metadata of these datasets) so we can show a dropdown for the user to choose from on the web interface. We have been using the list of datasets in the database. Is it synced with the datalab repo or does it need to be manually updated?

**Comment by neubig** [comment]
This is now available here: https://github.com/ExpressAI/DataLab/blob/main/utils/datasets_info.json

This still needs to be documented better in the ExplainaBoard at the very least.
