### ISSUE TITLE
Two problems with SST2 command line example

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#235]
The documentation is out of date so I'm working on fixing it: https://github.com/neulab/ExplainaBoard/pull/233

However, in the process I noticed two errors in the command line example from `sst2` included in the unit tests: https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/tests/test_cli.py

First, take the example of when the data is not read from datalab, using the following command:

    $ python -m explainaboard.explainaboard_main --task text-classification --dataset sst2 --system_outputs ./data/system_outputs/sst2/sst2-lstm-output.txt > /dev/null
    WARNING:datalabs.builder:Using custom data configuration default
    WARNING:datalabs.builder:Reusing dataset sst2 (/Users/gneubig/.cache/expressai/datalab/sst2/default/0.0.0/1cf5288b3b6fc8d192117283354266dc38a728c596c5910cda7ead9b0e3ab075)
    
    The dataset hasn't been supported by DataLab so no training set dependent features will
    be supported by ExplainaBoard. You can add the dataset by:
    https://github.com/ExpressAI/DataLab/blob/main/docs/SDK/add_new_datasets_into_sdk.md
    
    featurizing: 1821it [00:03, 458.08it/s]
    bucketing: 100%|██| 6/6 [00:00<00:00,  6.78it/s]
    the information of #label#
    bucket_interval	Accuracy	#samples
    [0,]	0.12981298129812982	909
    [1,]	0.10964912280701754	912
    
    ...

And then when the data is loaded from datalab:

$ python -m explainaboard.explainaboard_main --task text-classification --dataset sst2 --system_outputs ./data/system_outputs/sst2/sst2-lstm-output.txt > /dev/null
    WARNING:datalabs.builder:Using custom data configuration default
    WARNING:datalabs.builder:Reusing dataset sst2 (/Users/gneubig/.cache/expressai/datalab/sst2/default/0.0.0/1cf5288b3b6fc8d192117283354266dc38a728c596c5910cda7ead9b0e3ab075)
    
    The dataset hasn't been supported by DataLab so no training set dependent features will
    be supported by ExplainaBoard. You can add the dataset by:
    https://github.com/ExpressAI/DataLab/blob/main/docs/SDK/add_new_datasets_into_sdk.md
    
    featurizing: 1821it [00:03, 458.08it/s]
    bucketing: 100%|██| 6/6 [00:00<00:00,  6.78it/s]
    the information of #label#
    bucket_interval	Accuracy	#samples
    [0,]	0.12981298129812982	909
    [1,]	0.10964912280701754	912
    
    ...

It seems that
* [ ] Maybe the labels are flipped? I think a simple way to fix this is to just reverse the labels in the system output, but I want to make sure that this is indeed what happened.
* [ ] I'm sure sst2 is included in Datalab, but it's listed as not being found when looking up the features. I think this line is failing to find the data, but I'm not sure why? https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/processors/processor.py#L107

@pfliu-nlp or @lyuyangh  if you have a moment to look at this it'd be appreciated.

**Comment by neubig** [comment]
One follow-up note. For the latter problem it's strange, because for `ag_news`, looking up the stats in Datalab seems to work:

    >>> data_info = {'dataset_name': 'ag_news', 'subset_name': None, 'version': 'Hugging Face', 'transformation': {'type': 'origin'}}
    >>> response = requests.post(end_point_upload_dataset, json=data_info)
    >>> message = json.loads(response.text.replace("null", ""))["message"]
    >>> eprint(message)
    success

But for sst2 it does not:

    >>> data_info = {'dataset_name': 'sst2', 'subset_name': None, 'version': 'Hugging Face', 'transformation': {'type': 'origin'}}
    >>> response = requests.post(end_point_upload_dataset, json=data_info)
    >>> message = json.loads(response.text.replace("null", ""))["message"]
    >>> eprint(message)
    dataset does not exist

However, sst2 is definitely in the datalab database.

**Comment by lyuyangh** [comment]
hmm, @pfliu-nlp  would you have time to take a look at this? I'm not familiar with `read_statistics_from_db` (external stats). I didn't think this is an issue because I thought not every dataset has external stats but I'm not sure how it works.

**Comment by pfliu-nlp** [comment]
hi,
>"I'm sure sst2 is included in Datalab, but it's listed as not being found when looking up the features. I think this line is failing to find the data, but I'm not sure why?"
I guess the reason is:
currently, we will also calculate some training set dependent features and store them in MongoDB, which means there must be a dataset named `sst2` in MongoDB. There is one, but not in a consistent transformation. So that's why we could find sst2 finally.
Notably, two datasets will be considered as the same one when following types of information are the same:
* dataset_name
* subset_name
* version
* transformation
I'm working on this to fix this problem.
