### ISSUE TITLE
Add NLG tasks

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#29]
Currently the publicly available explainaboard code doesn't support NLG tasks, so this should be integrated.

**Comment by pfliu-nlp** [comment]
To achieve this, we should figure out if we assume we can get metric value (ROUGE, BERTScore) and attribute value (abstractiveness) beforehand (from user). Both are costly to calculate. What's your opinion?

**Comment by neubig** [comment]
Oh, I definitely think that these should be calculated within ExplainaBoard so that users can just upload outputs. If this causes computational issues we can think of ways to scale up I guess.

**Comment by neubig** [comment]
At least summarization is supported, so I'll close this issue, and we can add any other NLG tasks that we want as separate issues.
