### ISSUE TITLE
Introducing a unified & general interface for class serialization

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#302]
It's good to consider introducing a unified & general interface for `from_dict`

Some existing implementation & discussion
* https://github.com/neulab/ExplainaBoard/blob/aaf91a57f4a5c143a6f6c2aec33a81a3e51690b8/explainaboard/utils/serialization.py#L4
* https://github.com/neulab/ExplainaBoard/pull/301
* https://github.com/neulab/ExplainaBoard/blob/aaf91a57f4a5c143a6f6c2aec33a81a3e51690b8/explainaboard/feature.py#L43

**Comment by odashi** [comment]
Duplicate of #446, close anyway
