### ISSUE TITLE
Questions about datasets directory

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#35]
Hi @pfliu-nlp , I have a few questions about the datasets directory:

1. In the [README](https://github.com/neulab/ExplainaBoard/tree/main/dataset) it explains how to send a PR, but it doesn't explain what format the dataset should be in, where it should be placed, etc. (there are a few examples here but they seem to be system outputs, not the underlying data https://github.com/neulab/ExplainaBoard/tree/main/dataset/chunk_conll00/system_output)
2. What should I do in the case that a dataset consists of a few sub-datasets? For example, the same dataset has different dev/devtest/test splits, or contains data from different languages or domains?

**Comment by pfliu-nlp** [comment]
Since currently, ExplainaBoard doesn't regard training/dev/test sets as a necessity, we don't make requirements w.r.t format of datasets only if the format of the system output file can match.

**Comment by neubig** [comment]
Per our separate discussion, this will be handled along with #36
