### ISSUE TITLE
Enable squash merging by default

### ISSUE THREAD

**Issue by tetsuok** [neulab/ExplainaBoard#392]
Currently, when merging pull request, "Allow merge commits" is used. That makes commit history unnecessary long when pull request contains multiple commits, sometimes uninteresting commits. More importantly, merged commits makes harder to revert afterward. Enabling "Allow squash merging" in the settings avoids these issues.

Steps to enable squash merging are described as follows:

1. Go to https://github.com/neulab/ExplainaBoard/settings
2. Check "Allow squash merging". Uncheck the other options. See the screenshot below:

<img width="809" alt="Screen Shot 2022-08-23 at 17 27 19" src="https://user-images.githubusercontent.com/1183444/186112052-4dffa9af-74fa-4ea1-9459-146c6deb270f.png">

**Comment by tetsuok** [comment]
@neubig would you consider changing the way to merge pull requests as documented above?

**Comment by neubig** [comment]
Yes, and done!
