### ISSUE TITLE
Fixing naming convention of test code files

### ISSUE THREAD

**Issue by odashi** [neulab/ExplainaBoard#398]
Context:
https://github.com/neulab/ExplainaBoard/pull/396

This issue seems to be also a part of the contribution guideline:
https://github.com/neulab/ExplainaBoard/issues/376

We have currently two options for this convention:

* `test_<name>.<ext>`: `unittest`'s default convention.
* `<name>_test.<ext>`: unit tests have the same prefix name with its target.

**Comment by odashi** [comment]
@lyuyangh @tetsuok @neubig @pfliu-nlp Put comments if any.

**Comment by odashi** [comment]
I don't have strong opinions, but I've basically worked with the second option for a long time.

**Comment by tetsuok** [comment]
I don't have strong opinions about the naming conventions. I'm fine either way as long as some automation can detect filenames that don't follow the naming conventions in CI. For example, if we agree with using the second option, the CI system needs to detect and report files that use the first option.

**Comment by odashi** [comment]
Created #405 to apply several changes.

**Comment by odashi** [comment]
@tetsuok

> the CI system needs to detect and report files that use the first option.

It would be great if we have it, but I guess this also looks too much and it is actually hard to detect appropriately. E.g., imagine that we have `test_utils.py` that provides only utilities for testing but no any test cases.

**Comment by odashi** [comment]
As in #405 we are now using `*_test` format. Let me close this issue.
