### ISSUE TITLE
Consolidating docstring format

### ISSUE THREAD

**Issue by odashi** [neulab/ExplainaBoard#404]
Docstrings are sometimes written and sometimes not in this repository. There are also multiple styles applied to each docstring (reST style, Google style, and something else). To avoid this confusion, we need to decide some writing policy about docstrings.
Specifically, I realized we need to discuss at least:

- when we have to add docstrings
- which style is applied
- how to check docstrings

**Comment by odashi** [comment]
My opinion:

* when: at least every public class/function definitions that are used from other part of the codebase.
* style: No strong opinions, but I like Google's style because of its high readability.
* checking: There is a flake8 plugin https://pypi.org/project/flake8-docstrings/

**Comment by odashi** [comment]
RFC: @neubig @pfliu-nlp @tetsuok

**Comment by neubig** [comment]
* when: "at least every public class/function definitions that are used from other part of the codebase" sounds good to me
* style: I slightly prefer reST because it's marginally easier to write by hand, but also no strong preference
* checking: flake8 sounds great

**Comment by pfliu-nlp** [comment]
style:  I actually like `Google's style` since it's more intuitive, but I'm fine with reST if it could bring additional advantages.

**Comment by odashi** [comment]
The most significant difference between reST and Google styles is whether type information can be specified or not (`type` and `rtype` in reST), which was useful when Python didn't have any syntax of typing. Since we have type hints for the function signatures, this feature is probably outdated.
Google style guide also provides more fine-grained sections that are rarely used (such as `See Also:`)

**Comment by neubig** [comment]
OK, I'm happy to go with Google style, let's do it. Hopefully the conversion can be done automatically.

**Comment by tetsuok** [comment]
I don't have a strong opinion on this. I have been using Google style for a long time because it was easier to remember the format, though. I personally felt that the Google style was a bit easier to explain and to adopt the Google style for folks who aren't familiar with writing docstrings itself and reStructuredText (probably, the style guide also helped the adoption).

**Comment by odashi** [comment]
According to the discussion, we'd like to use Google's style. I'd prepare some pull requests to constrain it.
