### ISSUE TITLE
`bucket_interval` is type-ambiguous

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#431]
Currently `bucket_interval` is ambiguous in its typing, which is basically `tuple[float,float] | type[str,]` where the former is used for continuous values and latter is used for discrete values. 
https://github.com/neulab/ExplainaBoard/blame/main/explainaboard/analysis/performance.py#L11

We should probably change to the following:
```
bucket_interval: tuple[float,float] | None
bucket_name: str | None
```

**Comment by odashi** [comment]
I think `AnalysisCaseCollection`'s one should also be fixed:
https://github.com/neulab/ExplainaBoard/blob/6a85d3c51fd1f8eca8ddfdcba11d59181a183781/explainaboard/analysis/case.py#L89
