### ISSUE TITLE
DataLab logging is too verbose in integration tests

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#471]
Currently DataLab logs the progress of downloads, which leads to extremely large integration test logs ([example](https://github.com/neulab/ExplainaBoard/runs/8280314965?check_suite_focus=true)). We should be able to turn this logging off, at least for tests.

Based on [this](https://github.com/ExpressAI/DataLab/blob/5b860649520397e9c56bca3422912b241b2fa5a3/datalabs/utils/file_utils.py#L539) and [this](https://github.com/ExpressAI/DataLab/blob/main/datalabs/utils/logging.py#L86), it seems that probably:

```
datalabs.utils.logging.set_verbosity(datalabs.utils.logging.NOTSET)
```

would turn off the progress bar for downloading.

**Comment by tetsuok** [comment]
I think it makes more sense to fix the logic in `http_get` so that we can suppress progress message when the verbosity (the log level) is severe than `logging.INFO` as well.

**Comment by neubig** [comment]
Yeah, I agree.

**Comment by tetsuok** [comment]
Re-run integration tests with datalabs 0.4.11, but the issue still persists:
https://github.com/neulab/ExplainaBoard/runs/8293762905?check_suite_focus=true#step:5:467
