### ISSUE TITLE
Decompose MetricResult

### ISSUE THREAD

**Issue by odashi** [neulab/ExplainaBoard#477]
`MetricResult` has several information that are basically independent each other:

- A "value" with unspecified meaning.
- A confidence interval of "value"
- An agreement "value" (comes from `AuxiliaryMetricResult` which is used only to store Fleiss' Kappa).

Especially, there is an ambiguity between the "value" and auxiliary scores: we don't have any consensus to decide which number is "the value" of the metric.

To alleviate this confusion, I thought that `MetricResult` can be constructed as a set of values instead of having every field by itself, represented as follows:

```python
class MetricResult:
    config: MetricConfig
    values: dict[str, MetricValue]
```

where each `MetricValue` represents an individual statistical concept of the metric:

```python
class MetricValue:
    pass

class Score(MetricValue):
    value: float

class ConfidenceInterval(MetricValue):
    low: float
    high: float
    alpha: float
```

Using these definitions, we can represent the results as follows (for example):

```python
# Metric with agreement
MetricResult(
    config=config,
    values={
        "score": Score(value),
        "score_ci": ConfidenceInterval(low, high, alpha),
        "agreement": Score(agreement),
    },
)
```

This design has several benefits:

- We no longer need to determine which is the "value" of the metric. Each score has a distinctive name.
- We no longer need optional fields. Absence of the score is represented as just "no entry".
- Extensibility: it supports any number of results, and we can add new concepts by implementing a new `MetricValue`.
- Type information of `values` (`Score`, `CI` in this case) explicitly represents the concept of value.

RFC: @neubig @pfliu-nlp

**Comment by pfliu-nlp** [comment]
@odashi thanks for bringing this up!
I think it's a pretty elegant idea. When I tried to add the variable `agreement` I kinda feel that the `value` is not enough to use. We always have many statistical numbers (values) to be put in MetricResult.

One only concern is it will affect the DB schema a little bit.

**Comment by neubig** [comment]
This seems like a good idea overall!

There's always a tradeoff between defining things in classes (less flexible but less error-prone) or representing them as dictionaries (more flexible but more error-prone). It seems warranted in this case though, we'll just need to be careful to write unit tests to make sure that the metrics we implement generate things in the right format.

**Comment by odashi** [comment]
Applying this design also means that we no longer guarantee that every metric returns a specific entry (e.g., some metric may not generate "value" or "score").

In the future, I think it is also needed to introduce some interface to specify the representative key for a particular analysis. It would be good if we treat analyses on score/Ci/agreement equally, and avoid any hard-coded keys in the code.

**Comment by OscarWang114** [comment]
SGTM as well! I think the web interface is quite adaptable to this change.

I also like the idea of introducing representative keys, which the web interface potentially uses to avoid hard-coding as well.
