### ISSUE TITLE
Use setup.cfg to store every setup config

### ISSUE THREAD

**Issue by odashi** [neulab/ExplainaBoard#490]
Current `setup.py` follows a legacy pattern: writing settings in the code. Recent versions of setuptools supports to store most configs into `setup.cfg`, and we don't need writing setup "script" anymore.
This can avoid some complicated issues (typically circular imports) around `__version__`. `setup.cfg` can import/evaluate version file without any effects against code base.

The only issue here is the installation of `en_web_core_sm` spaCy package, which is performed at the last step of the `setup.py`. As I noted in #173, this is not a reliable way, and manually installing this package by users is much better than doing too much by us.

The underlying task in this issue is follows:

- [x] Move every setting in `setup.py` to `setup.cfg`.
- [ ] Remove ad-hoc installation of `en_web_core_sm` and add documentation about manual installation of it.

**Comment by tetsuok** [comment]
> Recent versions of distutil supports to store most configs into setup.cfg, and we don't need writing setup "script" anymore.

@odashi I guess [setuptools](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html)? It seems like distutils is [deprecated](https://docs.python.org/3/whatsnew/3.10.html#distutils).
