### ISSUE TITLE
t-test confidence level is wrong

### ISSUE THREAD

**Issue by odashi** [neulab/ExplainaBoard#510]
I found that the `alpha` parameter of the `scipy.stats.t.interval` **actually takes the exact confidence level $(1 - \alpha)$**.

<img width="676" alt="無題" src="https://user-images.githubusercontent.com/1023695/192571492-8bedbe8b-aa10-4e12-8c29-f1ffc3249612.png">

It looks the generated interval is wrongfully tight.
https://github.com/neulab/ExplainaBoard/blob/cc2d315695cec30e21d369362d1c76ca2ce9d40c/explainaboard/metrics/metric_test.py#L175-L180

**Comment by neubig** [comment]
Ah, we should fix this.
