### ISSUE TITLE
Lint Markdown files

### ISSUE THREAD

**Issue by tetsuok** [neulab/ExplainaBoard#536]
Currently, we manually check the syntax and style of Markdown files. The review process is time-consuming and can be inconsistent. It's better to automate the check so that reviewers can focus on the contents and clarity.

# Actions

- [x] Set up pre-commit and CI
- [ ] Fix all the remaining issues

**Comment by pfliu-nlp** [comment]
Hi, @tetsuok
A lot of new errors appeared regarding markdown lint when making a new PR, for example https://github.com/neulab/ExplainaBoard/actions/runs/3211437027/jobs/5249605967

**Comment by tetsuok** [comment]
@pfliu-nlp The linter found that the change doesn't follow the [rules](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md). It's not a bug in the linter. Found errors need to be fixed in the same way as we fix errors found by flake8.  Would you fix them?

**Comment by tetsuok** [comment]
@pfliu-nlp Some trivial errors can be fixed automatically by running 'pre-commit run markdownlint-cli2-fix --all-files'.

**Comment by neubig** [comment]
@tetsuok : I think the issue was probably that the PR that @pfliu-nlp was working on had not yet merged in the main branch. I just did it now, so let's see if that fixes the problem.

**Comment by tetsuok** [comment]
@neubig Ok. Thanks for the update.
