### ISSUE TITLE
Add "create documentation" to add_tasks.md

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#556]
There is a guide on how to add new tasks: https://github.com/neulab/ExplainaBoard/blob/main/docs/add_new_tasks.md

However it doesn't mention adding documentation, and it should. Here are some places where tasks should be added:
* https://github.com/neulab/ExplainaBoard/blob/main/docs/cli_interface.md
* https://github.com/neulab/ExplainaBoard/pull/553

**Comment by qjiang002** [comment]
Resolved in PR #553
