### ISSUE TITLE
New task: speech recognition

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#56]
Speech recognition is a standard generation task where the input is speech, output is text. For now, analysis could be done on the output side only.

* Evaluation metric: word error rate, character error rate
* Types of analysis: could be done on the level of individual deletions, substitutions, insertions. I have an example here: https://github.com/neubig/util-scripts/blob/master/counterrors.pl https://github.com/neubig/util-scripts/blob/master/error-diff.pl

**Comment by pfliu-nlp** [comment]
Sounds interesting: @neubig 
* has some datasets of this task been covered by huggingface dataset?
* do we have en example of the system output file?

**Comment by neubig** [comment]
* Yes, here's an example: https://huggingface.co/datasets/librispeech_asr
* I'll work on getting system outputs
