### ISSUE TITLE
add new field `description` to feature schema?

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#58]
- [x] add `description` into feature schema
 - [x] instantiation `description` field of existing supported tasks

**Comment by pfliu-nlp** [comment]
@OscarWang114 
A new field named `description` has been added into each feature, for example
![image](https://user-images.githubusercontent.com/59123869/151510256-213f044f-024d-4ba1-bcae-605ff800a7a4.png)

**Comment by neubig** [comment]
@pfliu-nlp if this is done the issue can be closed maybe?

**Comment by pfliu-nlp** [comment]
@OscarWang114 you can close this issue if you have been aware of this feature.

**Comment by OscarWang114** [comment]
Thanks for the information! Closing the issue.
