### ISSUE TITLE
CLI should allow automatic submission of results to web interface

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#60]
When doing analysis via the CLI it should allow automatic submission of results to the web interface (ideally by default), and return a link to where the results can be browsed.

@pfliu-nlp , could you take a look at this maybe together with @OscarWang114 and @lyuyangh ?

On the web interface it would include a visual browser of the results, and then also a place where you can download the json report (so the web interface could stand in as a complete replacement for the CLI).

**Comment by pfliu-nlp** [comment]
We have discussed this features previously with @OscarWang114 and @lyuyangh .  Maybe we can also dicuss  this Thursday for more details.

**Comment by OscarWang114** [comment]
Yes, we've previously discussed this feature together with the user account system. Auto-submission from CLI to the web interface can be achieved with API keys, which users need to download from the web interface and import to CLI, perhaps as an environment variable.

**Comment by neubig** [comment]
This probably shouldn't be included in the explainaboard sdk, but in the web server and a thin client. Closing here in favor of this issue: https://github.com/neulab/explainaboard_web/issues/143
