### ISSUE TITLE
Spacy model reload issue

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#66]
When fixed piaget issue, a new issue come out:
![image](https://user-images.githubusercontent.com/59123869/151909886-a879ddcd-b258-4c74-ab59-5d5ea5d5b90e.png)

**Comment by lyuyangh** [comment]
direct dependency in `install_requirements` is a relatively new feature. What version of python and pip are you using? I couldn't really find good documentation on this but
- for pip, could you try `python -m pip install --upgrade pip` and see if that fixes the issue?
- for python, I used python3.8 and python3.9. I think it works with both of them.

**Comment by lyuyangh** [comment]
Ohhhh, I see what you mean. CI is failing because of this. I'll take a look. Do you have any issue installing via `pip install .` locally?

**Comment by pfliu-nlp** [comment]
>"Do you have any issue installing via pip install . locally?"
I haven't test it locally, I will once I have the time.

**Comment by pfliu-nlp** [comment]
Hi, I actually can install it locally.
