### ISSUE TITLE
Extractive QA data format needs to be documented

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#70]
There is a [CLI example](https://github.com/neulab/ExplainaBoard/blob/main/docs/cli_examples.md) and [dataset](https://github.com/neulab/ExplainaBoard/blob/main/data/system_outputs/squad/testset-en.json) for extractive QA, but I wasn't able to easily guess what the dataset format is. I think we need some documentation for this, like we have for [text classification](https://github.com/neulab/ExplainaBoard/blob/main/docs/task_text_classification.md).

**Comment by pfliu-nlp** [comment]
https://github.com/neulab/ExplainaBoard/blob/main/docs/task_extractive_qa.md
