### ISSUE TITLE
Extractive QA CLI example is broken?

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#71]
The [CLI example](https://github.com/neulab/ExplainaBoard/blob/main/docs/cli_examples.md) for SQuAD extractive QA seems to output zero accuracy every time. This seems like a bug.

For example:

    "results": {
        "overall": [
            {
                "metric_name": "f1_score_qa",
                "value": "0",
                "confidence_score_low": "0",
                "confidence_score_up": "0"
            },
            {
                "metric_name": "exact_match_qa",
                "value": "0",
                "confidence_score_low": "0",
                "confidence_score_up": "0"
            }
        ],

Perhaps related to the file format: https://github.com/neulab/ExplainaBoard/issues/70

**Comment by pfliu-nlp** [comment]
fixed. Reason: wrong name of system output file
