### ISSUE TITLE
QA uses different ids for analysis and system output samples

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#73]

**Comment by pfliu-nlp** [comment]
This should be fixed.
@lyuyangh you can close the issue once you' are aware of this.

**Comment by lyuyangh** [comment]
Thanks a lot! I have verified that the ids are consistent for QA now but I found a new issue lol. QA now uses strings as ids but all the other tasks still use integers so the system output sample ID types aren't consistent for all tasks. The web app wouldn't be able to know when to search with a string and when to search with an integer. Could you update all the sample ids to use strings?

**Comment by pfliu-nlp** [comment]
OK, done. Hopefully it can pass the github action test.
