### ISSUE TITLE
Bugs: NER case printing

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#76]
`text` field should be the sample_id

![image](https://user-images.githubusercontent.com/59123869/152069693-6683a238-e6dd-4619-a852-b485a8f21d5e.png)

**Comment by pfliu-nlp** [comment]
should be fixed:
![image](https://user-images.githubusercontent.com/59123869/152075728-177c2f67-5253-4ac1-8095-1b44e382ff6b.png)

**Comment by pfliu-nlp** [comment]
@OscarWang114 you can close the issue once you informed of this.

**Comment by pfliu-nlp** [comment]
Also, I put one example report file of NER task here: https://github.com/neulab/ExplainaBoard/blob/main/data/reports/report_ner.json

**Comment by OscarWang114** [comment]
@pfliu-nlp Thanks for the info! Closing.
