### ISSUE TITLE
Suggestion: make system_outputs space-separated?

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#80]
Currently `system_outputs` is comma separated: https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/explainaboard_main.py#L48

However, this doesn't play super-well with some standard ways of doing things in Linux, which assume that multiple arguments are space separated. For example, the following don't work now but would work if we made it space separated:

    explainaboard --system_outputs my_outputs/*
    explainaboard --system_outputs my_outputs/{sys1,sys2,sys3}.tsv

What do you think about making `system_outputs` space separated @pfliu-nlp? I'm happy to make the change if it's OK. The main downside of doing this is that this is a very central part of the CLI and will break other code that uses explainaboard. However, it might be better to do it now than later (as it'll be hard to change later).

P.S.: I just noticed that currently the CLI only supports single system analysis 😄  If that's the case then obviously there's no upstream code using this at the moment, so it should be fine to change unless there's a strong argument for preferring comma separated.

**Comment by pfliu-nlp** [comment]
Good suggestion. We can revisit this issue once we have a consensus bout: https://github.com/neulab/ExplainaBoard/issues/81#issue-1122560907

**Comment by neubig** [comment]
I changed "*" to "+", but looks good!
