### ISSUE TITLE
CLI only supports single-system analysis

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#81]
As evidenced by the `NotImplementedError` here:
https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/explainaboard_main.py#L58

It would be nice to support analysis of multiple systems at the same time!

**Comment by pfliu-nlp** [comment]
We have discussed this with @OscarWang114 , @lyuyangh , since comparative analysis is not very interpretable in a local json file, we previously decided to make this part as a functionaltity implemented in the server side. Further discussion is welcome.
