### ISSUE TITLE
Extraneous message printed to stdout during analysis

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#82]
Currently explainaboard prints an extraneous message "Your request has been sent." to stdout during (some) analysis:

    $ explainaboard --task summarization --system_outputs ./data/system_outputs/cnndm/cnndm_mini.bart > report.json
    $ head -n 1 report.json
    Your request has been sent.

**Comment by pfliu-nlp** [comment]
I see. This is printed by another library `eaas` that ExplainaBoard for summarization tasks has used.  Maybe need some modifications there.

**Comment by pfliu-nlp** [comment]
This should be solved (don't forget to re-install the newst eaas library)

**Comment by neubig** [comment]
Confirmed!
