### ISSUE TITLE
It is not clear how to calculate different/additional metrics

### ISSUE THREAD

**Issue by neubig** [neulab/ExplainaBoard#83]
According to the documentation, multiple metrics are supported for the summarization task:
https://github.com/neulab/ExplainaBoard/blob/main/docs/supported_tasks.md#summarization

However, by default only BLEU is printed in the output JSON, and none of the documentation I can find tells me how I can print out (some variety of) ROUGE instead.

**Comment by pfliu-nlp** [comment]
Thanks for capturing this. I will refine this part ASAP!

**Comment by pfliu-nlp** [comment]
Almost done: https://github.com/neulab/ExplainaBoard/blob/main/docs/supported_tasks.md#summarization
There are some metrics not being introduced currently due to some upstream bugs of eaas.

**Comment by pfliu-nlp** [comment]
should support more now (https://github.com/ExpressAI/EaaS_API_dev/issues/27#issue-1123515003)
