### ISSUE TITLE
NER returns the same fine-grained results for all buckets?

### ISSUE THREAD

**Issue by OscarWang114** [neulab/ExplainaBoard#88]
I submitted the NER system output in the artifacts directory to the SDK. Below is the generated analysis. All buckets in "sentence_length" returned identical cases in bucket samples (a total of 1010). Possibly a bug?
<img width="505" alt="Screen Shot 2022-02-10 at 3 22 32 PM" src="https://user-images.githubusercontent.com/30998659/153505777-b9f39d0b-496a-4165-b830-d35e51e45cbb.png">

**Comment by pfliu-nlp** [comment]
should be fixed. see new report example: https://raw.githubusercontent.com/neulab/ExplainaBoard/main/data/reports/report_ner.json

also, added a new feature for ner

**Comment by pfliu-nlp** [comment]
Also, added the url of system output files fro instruction (@lyuyangh ): https://github.com/neulab/ExplainaBoard/blob/2e0ae0d3c4ee874800822449e876b6216cb4a644/explainaboard/tasks.py#L67
