### ISSUE TITLE
New Task: Metaphor QA

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/ExplainaBoard#94]
Dataset: https://github.com/nightingal3/metaphor-qa
Format of system output: 
```[ 
{ "question": ..., "answer1": ..., "answer2": , ..., "true_label": ...}, ...
]
```

**Comment by pfliu-nlp** [comment]
Maybe also add this dataset into DataLab
https://github.com/ExpressAI/DataLab/issues/25#issuecomment-1045201114

**Comment by neubig** [comment]
I think we should just treat this as a standard "multi-choice QA" dataset (like Hellaswag, which is already included). Could we generalize Hellaswag's schema to also cover this and other multi-choice QA datasets, like the ones included in unified-QA https://arxiv.org/abs/2005.00700

**Comment by pfliu-nlp** [comment]
This should not be difficult. 
But I'm still looking into the [dataset format of metaphor-qa](https://github.com/nightingal3/metaphor-qa/blob/master/data/filtered/train.csv), it seems a little confused and I probably will consult Emmy.

**Comment by pfliu-nlp** [comment]
Agree. A good opportunity to eat off QA tasks, (hopefully, together with another big task: mt)

**Comment by pfliu-nlp** [comment]
The dataset `metaphor_qa` has been added into (1) sdk (2) web analysis platform of DataLab.
Relevant discussion: https://github.com/ExpressAI/DataLab/issues/86#issue-1145907487

**Comment by neubig** [comment]
This has been added for now. There are some other related issues in making a leaderboard, which we're working on separately.
